### ISSUE TITLE
Killed when compile more than 9 files

### ISSUE THREAD

**Issue by ng4pw** [SunWeb3Sec/DeFiHackLabs#227]
why my command got killed?
i'm using github codespaces

![image](https://user-images.githubusercontent.com/59191842/218501998-9fc3a58c-1de5-4c6c-97eb-254e1e043825.png)

**Comment by SunWeb3Sec** [comment]
HI @ng4pw Did you try to remove cache before?

**Comment by ng4pw** [comment]
> HI @ng4pw Did you try to remove cache before?

no, i tried and still got error.
only got Killed in some VPS (codespaces and code***where)

**Comment by SunXrex** [comment]
@ng4pw it's memory issue. It probably ran out of memory. 
kernel killing the process.  This happens in Rust repos.

The answer checked from foundry channel.

**Comment by SunWeb3Sec** [comment]
@ng4pw it's memory issue. It probably ran out of memory.
kernel killing the process. This happens in Rust repos.

The answer checked from foundry channel.

**Comment by ng4pw** [comment]
that's correct, thank you
