### ISSUE TITLE
Question Regarding Improving the Completeness of Certain EXP Files

### ISSUE THREAD

**Issue by Autosaida** [SunWeb3Sec/DeFiHackLabs#413]
Hello, I have noticed that some of the EXP files in this repository may not be as comprehensive as they could be. I would like to inquire about the preferred method for enhancing their completeness. Should I make substantial changes directly to the original EXP files (possibly involving many changes), or is it advisable to create new ones named as "exp2"?

**Comment by SunXrex** [comment]
Hi @Autosaida Create exp2 is more better. Thanks a lot!

**Comment by SunWeb3Sec** [comment]
Hi @Autosaida Create exp2 is more better. Thanks a lot!

**Comment by Autosaida** [comment]
Ok, I got it. Thx.
