### ISSUE TITLE
Request for Translation of the First Four Articles in the DefiHackLabs onchain_debug Course into Simplified Chinese

### ISSUE THREAD

**Issue by charliex2** [SunWeb3Sec/DeFiHackLabs#581]
Hi,

I am a Solidity learner who recently came across your [onchain_debug course](https://github.com/SunWeb3Sec/DeFiHackLabs/tree/main/academy/onchain_debug). I noticed that the first four articles are written in Traditional Chinese, while the subsequent 5-7 articles are in Simplified Chinese. For learners who are more comfortable with Simplified Chinese, this may pose a slight comprehension barrier.

I am eager to contribute to the course by translating the initial four articles into Simplified Chinese to make the content more accessible to a wider audience. I would like to inquire whether you welcome the submission of a Pull Request for this translation task. If you have any specific guidelines or preferences, I am open to discussion and would appreciate your guidance.

Thank you for your time and effort. I look forward to potentially contributing to the enhancement of this course.

**About the Difference Between Simplified and Traditional Chinese:**
Simplified Chinese and Traditional Chinese are two different writing forms of the Chinese language. Traditional Chinese characters have more complex strokes, while Simplified Chinese characters are streamlined and simplified, a result of a character simplification movement in the 1950s and 60s. Although both forms share the same linguistic foundation, they may differ in character structure, word usage, and expression conventions.

**Comment by SunWeb3Sec** [comment]
I think it's fine now so many translators :D
