### ISSUE TITLE
Readme links don't target right file

### ISSUE THREAD

**Issue by Elyx0** [SunWeb3Sec/DeFiHackLabs#811]
Ie: Penpie / Aave / Zen, the .py adds _exp to filename but not for Readme link.

**Comment by SunWeb3Sec** [comment]
Hi @akshaynexus Can you take a look?

**Comment by akshaynexus** [comment]
@Elyx0 please give a reproduceable flow i can use to debug the issue

from what i see the readme link directs it to the file properly

**Comment by Elyx0** [comment]
Check the add new entry python script from CONTRIBUTING.md add a fake entry and then try to click it from the updated README.md it will link to the wrong place
