### ISSUE TITLE
Use the latest() repo,  which use "cheats.createSelectFork" appear errors.

### ISSUE THREAD

**Issue by sodexx7** [SunWeb3Sec/DeFiHackLabs#9]
[FAIL. Reason: Setup failed: Invalid data] setUp() (gas: 0)

**Comment by SunWeb3Sec** [comment]
Hi @sodexx7 Have you updated foundry? Please run foundryup to update. It should works.

**Comment by sodexx7** [comment]
@SunWeb3Sec  Yeah, when I upgrade foundry. It can work. Thanks for your answer.
